### ISSUE TITLE
Null pointer crash

### ISSUE THREAD

**Issue by MDSergioMD** [airbnb/lottie-android#1794]
Null pointer exception crash reported on google play, cant reproduce it my self. Crash log is from the latest 3.7.0 ver.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect f.b.a.d.b()' on a null object reference
       at com.airbnb.lottie.LottieDrawable.getMaxScale(LottieDrawable.java:1208)
       at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1263)
       at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:407)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:397)
       at android.widget.ImageView.onDraw(ImageView.java:1505)
       at android.view.View.draw(View.java:21618)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.draw(View.java:21621)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401)
       at android.view.View.updateDisplayListIfDirty(View.java:20441)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3840)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3648)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2954)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
       at android.view.Choreographer.doCallbacks(Choreographer.java:875)
       at android.view.Choreographer.doFrame(Choreographer.java:776)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

**Comment by KatherineStrider** [comment]
Hello. We found a similar crash. It was not possible to reproduce, however, in firebase analytics there are about 20 such cases.

Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference

```
com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.getMatrix (TransformKeyframeAnimation.java:171)
com.airbnb.lottie.model.layer.BaseLayer.draw (BaseLayer.java:237)
com.airbnb.lottie.model.layer.CompositionLayer.drawLayer (CompositionLayer.java:120)
com.airbnb.lottie.model.layer.BaseLayer.draw (BaseLayer.java:239)
com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio (LottieDrawable.java:1247)
com.airbnb.lottie.LottieDrawable.drawInternal (LottieDrawable.java:393)
com.airbnb.lottie.LottieDrawable.draw (LottieDrawable.java:383)
android.widget.ImageView.onDraw (ImageView.java:1532)
android.view.View.draw (View.java:21618)
android.view.View.updateDisplayListIfDirty (View.java:20483)
android.view.View.draw (View.java:21350)
android.view.ViewGroup.drawChild (ViewGroup.java:4446)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4205)
androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw (ConstraintLayout.java:1975)
android.view.View.updateDisplayListIfDirty (View.java:20474)
android.view.View.draw (View.java:21350)
android.view.ViewGroup.drawChild (ViewGroup.java:4446)
androidx.recyclerview.widget.RecyclerView.drawChild (RecyclerView.java:5030)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4205)
android.view.View.draw (View.java:21621)
androidx.recyclerview.widget.RecyclerView.draw (RecyclerView.java:4429)
android.view.View.updateDisplayListIfDirty (View.java:20483)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4428)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4401)
android.view.View.updateDisplayListIfDirty (View.java:20441)
android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:584)
android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:590)
android.view.ThreadedRenderer.draw (ThreadedRenderer.java:668)
android.view.ViewRootImpl.draw (ViewRootImpl.java:3840)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3648)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2954)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1857)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8089)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1057)
android.view.Choreographer.doCallbacks (Choreographer.java:875)
android.view.Choreographer.doFrame (Choreographer.java:776)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1042)
android.os.Handler.handleCallback (Handler.java:888)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:213)
android.app.ActivityThread.main (ActivityThread.java:8178)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)
```

**Comment by Angelia64** [comment]
> Null pointer exception crash reported on google play, cant reproduce it my self. Crash log is from the latest 3.7.0 ver.
> 
> `Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect f.b.a.d.b()' on a null object reference at com.airbnb.lottie.LottieDrawable.getMaxScale(LottieDrawable.java:1208) at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1263) at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:407) at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:397) at android.widget.ImageView.onDraw(ImageView.java:1505) at android.view.View.draw(View.java:21618) at android.view.View.updateDisplayListIfDirty(View.java:20483) at android.view.View.draw(View.java:21350) at android.view.ViewGroup.drawChild(ViewGroup.java:4446) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205) at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975) at android.view.View.draw(View.java:21621) at android.view.View.updateDisplayListIfDirty(View.java:20483) at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428) at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401) at android.view.View.updateDisplayListIfDirty(View.java:20441) at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584) at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590) at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668) at android.view.ViewRootImpl.draw(ViewRootImpl.java:3840) at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3648) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2954) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057) at android.view.Choreographer.doCallbacks(Choreographer.java:875) at android.view.Choreographer.doFrame(Choreographer.java:776) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042) at android.os.Handler.handleCallback(Handler.java:888) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:213) at android.app.ActivityThread.main(ActivityThread.java:8178) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

Get a fucking life 88

**Comment by lsuski** [comment]
I have random crash (lottie `4.2.1`)
```
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
    at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.getMatrix(TransformKeyframeAnimation.java:172)
    at com.airbnb.lottie.model.layer.BaseLayer.getBounds(BaseLayer.java:217)
    at com.airbnb.lottie.model.layer.CompositionLayer.getBounds(CompositionLayer.java:128)
    at com.airbnb.lottie.model.layer.CompositionLayer.getBounds(CompositionLayer.java:131)

**Comment by gpeal** [comment]
@lsuski This should be resolved by the above PR.

**Comment by lsuski** [comment]
Isn't above PR in lottie 4.2.1? I'm using it and still have this crash. I've looked into changes and it doesn't seem to fix this one. The problem is that there is a position but `null` value in it and there is no `positionValue` null check

**Comment by gpeal** [comment]
No it's not

**Comment by lsuski** [comment]
Do you mean that #1917 is not part of lottie `4.2.1`? But it is in the changelog. Even if not there is still no `positionValue` null check in `getMatrix`

**Comment by gpeal** [comment]
@lsuski Sorry, my mistake. I forgot that that PR made it in for that release. Do you mind opening a new issue with this stack?

**Comment by lsuski** [comment]
Sure, no problem
